name: Development Blog
url: "https://akpw.github.io"
baseurl: ""
description: ' on software and related things'

#exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Arseniy Kuznetsov'
disqus_shortname: akpdev
google_analytics: UA-77964245-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
